apiVersion: apps/v1
kind: Deployment
metadata:
  name: remibot
  namespace: feavy
  labels:
    k8s-app: remibot
spec:
  selector:
    matchLabels:
      k8s-app: remibot
  template:
    metadata:
      labels:
        k8s-app: remibot
        name: remibot
    spec:
      containers:
        - name: remibot
          image: ${DOCKER_IMAGE}
          command: ["java", "-jar", "remibot.jar", "${BOT_TOKEN}"]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/data
              name: remibot-data
      volumes:
        - name: remibot-data
          hostPath:
            path: /mnt/remibot
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: 'oracle-paris'
