name: Java CI-CD with Gradle and Azure

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jars
        path: |
          build/libs
    - uses: feavy/deploy@main
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        GITHUB_USERNAME: feavy
        GITHUB_TOKEN: ${{ secrets.PAT }}
        DOCKERFILE_PATH: .
        DOCKER_IMAGE: remibot:latest
        DEPLOYMENT: deployment.yml
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        PLATFORM: arm64
    - name: Restart deployment
      run: kubectl rollout restart deployment remibot --namespace feavy